services:
  - type: web
    name: mixology-order-advisor
    runtime: node
    buildCommand: npm install serve
    startCommand: npx serve -s . -l 10000
    branch: main
    rootDir: .
    autoDeploy: true
    healthCheckPath: /
    plan: starter
